"""empty message

Revision ID: 190c01521f76
Revises: 1bb7cfc58ecd
Create Date: 2024-09-20 21:28:43.331725

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '190c01521f76'
down_revision = '1bb7cfc58ecd'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('posts', schema=None) as batch_op:
        batch_op.drop_index('slug')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('posts', schema=None) as batch_op:
        batch_op.create_index('slug', ['slug'], unique=True)

    # ### end Alembic commands ###
